In [1]:
%matplotlib inline

import matplotlib.pyplot as plt
import numpy as np
import tensorflow as tf
tf.enable_eager_execution()

In [2]:
class_ids = [1, 1, 3, 2, 3]

n = 5
w = 200
h = 200
class_n = 4
mask = np.zeros((n, w, h, class_n))

for i, class_id in enumerate(class_ids):
    mask[i, :, :, class_id] = class_id

In [3]:
mask.mean(axis=1).mean(axis=1)

array([[0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 3.],
       [0., 0., 2., 0.],
       [0., 0., 0., 3.]])

In [6]:
mask[tf.range(0, tf.shape(mask)[0]), :, :, class_ids].shape

(5, 200, 200)

In [5]:
for i, class_id in enumerate(class_ids):
    print(mask[i, :, :, class_id].shape)

(200, 200)
(200, 200)
(200, 200)
(200, 200)
(200, 200)


In [6]:
nmask.mean(axis=1).mean(axis=1)

array([[1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [0., 0., 3., 0., 3.],
       [0., 0., 0., 2., 0.],
       [0., 0., 3., 0., 3.]])

In [15]:
indices = tf.range(0, tf.shape(mask)[0])
tclass_ids = tf.constant(class_ids)

def select_mask(args):
    i = args[0]
    single_mask = args[1]
    
    return i, single_mask[:, :, tclass_ids[i]]
    
_, rmask = tf.map_fn(select_mask, (indices, mask))
rmask.numpy().shape

(5, 200, 200)

In [14]:
rmask = tf.zeros((n, w, h))
for i, class_id in enumerate(class_ids):
    rmask[i] = mask[i, :, :, class_id]

TypeError: 'EagerTensor' object does not support item assignment

In [26]:
rmask = tf.gather(mask, classs_ids, axis=-1).numpy()
rmask.shape

(5, 200, 200, 5)

In [ ]:
tf.map_fn()

In [25]:
rmask.numpy().mean(axis=1).mean(axis=1)

array([1., 1., 3., 2., 3.])